### ISSUE TITLE
Bug HATEOAS

### ISSUE THREAD

**Issue by yks095** [DND-PickMe/pickme-back#81]
- `http://..` 로 되어있는 `HATEOAS`를 `https://..` 로 변경

**Comment by mkshin96** [comment]
API Guide의 `http://localhost:8080`도 `https://pickme-back.ga` 로 수정하였음.

**Comment by mkshin96** [comment]
`셀프인터뷰`, `프로젝트` ... 가 삭제되어 반환되는 객체 내의 `account`에 삭제된 `셀프인터뷰`, `프로젝트` 등이 남아있는 버그까지 수정해야 함.
